title: Esayas F. Gebresilasie
logo: /assets/images/profile.png
description: Mobile App Developer 
theme: jekyll-theme-minimal
url: [View My GitHub]("https://addiscodr.github.io"){:target="_blank"}
baseurl: ""






