title: Esayas F. Gebresilasie
logo: /assets/img/my_pic.png
description: Mobile App Developer | Flutter . NodeJS . Firebase . Hive . Sqflite 
theme: jekyll-theme-minimal
show_downloads: false
github_username: addiscodr
linkedin_username: addiscodr
sass:
  style: compressed






