title: Esayas F. Gebresilasie
logo: /assets/img/my_pic.png
description: Mobile App Developer 
theme: jekyll-theme-minimal
social_links:
   linkedin:
      https://linkedin.com/in/addiscodr
   whatsapp:
      https://wa.me/251911108121
sass:
  style: compressed
url: "https://addiscodr.github.io"
baseurl: ""






